In [1]:
import pandas as pd

high = pd.read_csv("../data/high_popularity_spotify_data.csv")
low = pd.read_csv("../data/low_popularity_spotify_data.csv")

In [2]:
high.head()

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.122,0.535,"Lady Gaga, Bruno Mars",3,0.0304,...,0.0000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.117,0.438,Billie Eilish,4,0.0358,...,0.0608,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.159,0.372,Gracie Abrams,4,0.0368,...,0.0000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.304,0.786,Sabrina Carpenter,4,0.0634,...,0.0000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.355,0.939,"ROSÉ, Bruno Mars",4,0.2600,...,0.0000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M

In [3]:
high.shape

(1686, 29)

In [4]:
high.info()

<class 'pandas.DataFrame'>
RangeIndex: 1686 entries, 0 to 1685
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   energy                    1686 non-null   float64
 1   tempo                     1686 non-null   float64
 2   danceability              1686 non-null   float64
 3   playlist_genre            1686 non-null   str
 4   loudness                  1686 non-null   float64
 5   liveness                  1686 non-null   float64
 6   valence                   1686 non-null   float64
 7   track_artist              1686 non-null   str
 8   time_signature            1686 non-null   int64
 9   speechiness               1686 non-null   float64
 10  track_popularity          1686 non-null   int64
 11  track_href                1686 non-null   str
 12  uri                       1686 non-null   str
 13  track_album_name          1685 non-null   str
 14  playlist_name             1686 non-null   str
 15  analysis_url              1686 non-null   str
 16  track_id                  1686 non-null   str
 17  track_name                1686 non-null   str
 18  track_album_release_date  1686 non-null   str
 19  instrumentalness          1686 non-null   float64
 20  track_album_id            1686 non-null   str
 21  mode                      1686 non-null   int64
 22  key                       1686 non-null   int64
 23  duration_ms               1686 non-null   int64
 24  acousticness              1686 non-null   float64
 25  id                        1686 non-null   str
 26  playlist_subgenre         1686 non-null   str
 27  type                      1686 non-null   str
 28  playlist_id               1686 non-null   str
dtypes: float64(9), int64(5), str(15)
memory usage: 382.1 KB

In [5]:
high_dp = high[high.duplicated(subset='track_name', keep=False)]
high_dp[['track_name', 'track_artist', 'track_id']].sort_values(by='track_name')

,track_name,track_artist,track_id
43,+57,"KAROL G, Feid, DFZM, Ovy On The Drums, J Balvi...",3mg9jYNC1NihbthlglzrWP
273,+57,"KAROL G, Feid, DFZM, Ovy On The Drums, J Balvi...",3mg9jYNC1NihbthlglzrWP
1317,+57,"KAROL G, Feid, DFZM, Ovy On The Drums, J Balvi...",3mg9jYNC1NihbthlglzrWP
211,3 Headed Goat (feat. Lil Baby & Polo G),"Lil Durk, Lil Baby, Polo G",6Tguhaf2uAe6OjRLsR2Tql
777,3 Headed Goat (feat. Lil Baby & Polo G),"Lil Durk, Lil Baby, Polo G",6Tguhaf2uAe6OjRLsR2Tql
...,...,...,...
554,née-nah,"21 Savage, Travis Scott, Metro Boomin",2yUzr8Sr6ldG8vmHhZwTnz
191,née-nah,"21 Savage, Travis Scott, Metro Boomin",2yUzr8Sr6ldG8vmHhZwTnz
725,we can't be friends (wait for your love),Ariana Grande,51ZQ1vr10ffzbwIjDCwqm4
31,we can't be friends (wait for your love),Ariana Grande,46kspZSY3aKmwQe7O77fCC
500,we can't be friends (wait for your love),Ariana Grande,46kspZSY3aKmwQe7O77fCC

In [6]:
low.head()
low.info()

low.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 3145 entries, 0 to 3144
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time_signature            3144 non-null   float64
 1   track_popularity          3145 non-null   int64
 2   speechiness               3144 non-null   float64
 3   danceability              3144 non-null   float64
 4   playlist_name             3145 non-null   str
 5   track_artist              3145 non-null   str
 6   duration_ms               3144 non-null   float64
 7   energy                    3144 non-null   float64
 8   playlist_genre            3145 non-null   str
 9   playlist_subgenre         3145 non-null   str
 10  track_href                3144 non-null   str
 11  track_name                3145 non-null   str
 12  mode                      3144 non-null   float64
 13  uri                       3144 non-null   str
 14  type                      3144 non-null   str
 15  track_album_release_date  3145 non-null   str
 16  analysis_url              3144 non-null   str
 17  id                        3144 non-null   str
 18  instrumentalness          3144 non-null   float64
 19  track_album_id            3145 non-null   str
 20  playlist_id               3145 non-null   str
 21  track_id                  3145 non-null   str
 22  valence                   3144 non-null   float64
 23  key                       3144 non-null   float64
 24  tempo                     3144 non-null   float64
 25  loudness                  3144 non-null   float64
 26  acousticness              3144 non-null   float64
 27  liveness                  3144 non-null   float64
 28  track_album_name          3145 non-null   str
dtypes: float64(13), int64(1), str(15)
memory usage: 712.7 KB

time_signature              1
track_popularity            0
speechiness                 1
danceability                1
playlist_name               0
track_artist                0
duration_ms                 1
energy                      1
playlist_genre              0
playlist_subgenre           0
track_href                  1
track_name                  0
mode                        1
uri                         1
type                        1
track_album_release_date    0
analysis_url                1
id                          1
instrumentalness            1
track_album_id              0
playlist_id                 0
track_id                    0
valence                     1
key                         1
tempo                       1
loudness                    1
acousticness                1
liveness                    1
track_album_name            0
dtype: int64

In [7]:
low_dp = low[low.duplicated(subset='track_name', keep=False)]
low_dp[['track_name', 'track_artist', 'track_id']].sort_values(by='track_name')

,track_name,track_artist,track_id
87,AZAMAN,Rema,4K5lYtD8r6OFRbzWc6MwCS
421,AZAMAN,Rema,4K5lYtD8r6OFRbzWc6MwCS
1056,Albaizyn,lorleaf,3Qj2ViqEZ2niYq4s8R4Xyw
183,Albaizyn,lorleaf,3Qj2ViqEZ2niYq4s8R4Xyw
2597,Ani Maamin,DJ Kraz,4rUpJVSmkIZhXYJK9QpEzh
...,...,...,...
1277,glow,"Fred again.., Duskus, Four Tet, Joy Anonymous,...",3i9QKRl5Ql3pgUfNdYBVTc
1013,letting go,mood.,4PCMttKgDScL8IbN59lF11
1648,letting go,"Fireboy DML, Lojay",4VmZWEvWcmWFqg7GciQM88
1176,Éphémère,Tony Anderson,4LurYqydfPdLc9IN7eQxTF
2363,Éphémère,Tony Anderson,4LurYqydfPdLc9IN7eQxTF